[platformio]
default_envs = esp32dev

[env]
platform = espressif32@7.0.1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_unflags = -std=gnu++11
lib_deps =
    lvgl/lvgl@9.5.0
    zinggjm/GxEPD2@1.6.9
    h2zero/NimBLE-Arduino@2.5.1
    bblanchon/ArduinoJson@7.4.3
build_flags =
    -std=gnu++17
    -I include
    -D LV_CONF_INCLUDE_SIMPLE
    -D EPD_TOOLKIT_VERSION=\"0.3.0\"
    -Wall
    -Wextra
    -Wno-unused-parameter

[env:esp32dev]
board = esp32dev
board_build.partitions = huge_app.csv
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
build_type = debug
build_flags =
    ${env.build_flags}
    -D CORE_DEBUG_LEVEL=3

[env:esp32dev_release]
board = esp32dev
board_build.partitions = huge_app.csv
build_type = release
build_flags =
    ${env.build_flags}
    -D EPD_TOOLKIT_RELEASE=1
    -D CORE_DEBUG_LEVEL=0

[env:esp32_e029a01]
board = esp32dev
board_build.partitions = huge_app.csv
build_type = debug
build_flags =
    ${env.build_flags}
    -D EPD_PANEL_E029A01=1
    -D CORE_DEBUG_LEVEL=3

[env:esp32_e029a01_release]
board = esp32dev
board_build.partitions = huge_app.csv
build_type = release
build_flags =
    ${env.build_flags}
    -D EPD_PANEL_E029A01=1
    -D EPD_TOOLKIT_RELEASE=1
    -D CORE_DEBUG_LEVEL=0

[env:esp32c3_e029a01]
board = airm2m_core_esp32c3
board_build.partitions = huge_app.csv
build_type = debug
build_flags =
    ${env.build_flags}
    -D EPD_PANEL_E029A01=1
    -D CORE_DEBUG_LEVEL=3

[env:esp32c3_e029a01_release]
board = airm2m_core_esp32c3
board_build.partitions = huge_app.csv
build_type = release
build_flags =
    ${env.build_flags}
    -D EPD_PANEL_E029A01=1
    -D EPD_TOOLKIT_RELEASE=1
    -D CORE_DEBUG_LEVEL=0

[env:native]
platform = native
framework =
lib_deps =
test_framework = unity
test_build_src = no
build_unflags =
build_flags =
    -std=gnu++17
    -I include
